proyecto/tesis/apps/custom_auth/urls.py
__author__ = 'diegazo'

from django.conf.urls import include, url
from tesis.apps.custom_auth import views

urlpatterns = [
	url(r'^login/$', views.Login_view, name='vista_login'), #Vista Login
    url(r'^logout/$',views.Salir_view, name='vista_salir'), #Vista LogOut
    url(r'^lockScreen/$',views.LockScreen_view, name='vista_bloquear'), #Vista Bloquear Usuario
    url(r'^$', views.demo_view, name='vista_demo'), #Vista Demo
    url(r'^charge/add/$', views.Cargos_view, name='crear-cargo'), #Vista Crear Cargo
    url(r'^charge/(?P<pk>\d+)/delete/$', views.CargoDelete, name='borrar-cargo'), #Vista Borrar Cargo
    url(r'^charge/(?P<pk>\d+)/cargar/$', views.ActualizarDatos, name='cargar-cargo'), #Vista Actualizar Cargo
    url(r'^user/add/$', views.CrearUser_View, name='crear-user'), #Vista Crear User
    url(r'^user/(?P<hash>\w+)/profile/$', views.Perfiles_view, name='crear-perfil'), #Vista Crear User
    url(r'^directory/$', views.Directorio_view, name='vista-dir'), #Vista Directorio
]

proyecto/tesis/apps/gestion/urls.py
__author__ = 'diegazo'

from django.conf.urls import include, url
from tesis.apps.gestion import views

urlpatterns = [ # las urls son mas lindas en ingles
	url(r'^management/catering/$', views.Abastecimiento_view, name='crear-abast'), #Vista Crear Categoria
	url(r'^management/ws/products/$', views.ws_productos, name='ws-productos'), #Vista Crear Categoria
	#url(r'^category/(?P<pk>\d+)/delete/$', views.CategoriaDelete, name='borrar-cat'), #Vista Borrar Categoria
    #url(r'^category/(?P<pk>\d+)/cargar/$', views.ActualizarDatosCat, name='cargar-cat'), #Vista Actualizar Categoria
]

proyecto/tesis/apps/productos/urls.py
__author__ = 'diegazo'

from django.conf.urls import include, url
from tesis.apps.productos import views

urlpatterns = [ # las urls son mas lindas en ingles 
	url(r'^product/list/$', views.ListadoProductosView, name='ProductList'), #Ejemplo Vista Productos
	url(r'^category/add/$', views.Categorias_view, name='crear-cat'), #Vista Crear Categoria
	url(r'^category/(?P<pk>\d+)/delete/$', views.CategoriaDelete, name='borrar-cat'), #Vista Borrar Categoria
    url(r'^category/(?P<pk>\d+)/cargar/$', views.ActualizarDatosCat, name='cargar-cat'), #Vista Actualizar Categoria
    url(r'^product/add/$', views.Productos_view, name='crear-prod'), #Vista Crear Productos
    url(r'^product/(?P<pk>\d+)/delete/$', views.ProductoDelete, name='borrar-prod'), #Vista Borrar Productos
    url(r'^product/(?P<pk>\d+)/cargar/$', views.ActualizarDatosProd, name='cargar-prod'), #Vista Actualizar Productos
]
                

proyecto/tesis/urls.py
#Este es el main de url, osea que este archivo reune las urls de tus apps
# Sorry por no poder hablar pero si nos conectamos mas temprano aulamos.



from django.conf.urls import include, url
from django.contrib import admin


admin.site.site_header = 'Escuela de Parvulos'

urlpatterns = [
	
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tesis.apps.custom_auth.urls')), #<- aqui llamo la url de la app de custom_auth
    url(r'^', include('tesis.apps.productos.urls')), #<- aqui llamo la url de la app de productos
    url(r'^', include('tesis.apps.gestion.urls')), #<- aqui llamo la url de la app de gestion
]

proyecto/tesis/apps/gestion/models.py
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
#Importamos el modelo de productos
from tesis.apps.custom_auth.models import UserProfile
from tesis.apps.productos.models import ModeloProductos, ModeloCategoriaProd
from django.utils import timezone

# Para enviar señales a otros modelos o apps
from django.db.models.signals import post_save
from django.dispatch import receiver

# Creamos las gestiones de SALIDA Y ENTRADA
# Segun convencion los nombres de los campos en los modelos deben ser
# escritos en minusculas separados por un guion bajo.
# https://docs.djangoproject.com/en/1.11/internals/contributing/writing-code/coding-style/#model-style

#Entrada
class ModeloAbast(models.Model):
	solicitante = models.ForeignKey(UserProfile)
	categoria = models.ForeignKey(ModeloCategoriaProd)
	producto = models.ForeignKey(ModeloProductos)
	cantidad = models.IntegerField()
	fecha = models.DateTimeField(auto_now_add=True)





#Salida
class ModeloPedido(models.Model):
	solicitante = models.ForeignKey(UserProfile)
	categoria = models.ForeignKey(ModeloCategoriaProd)
	producto = models.ForeignKey(ModeloProductos)
	cantidad = models.IntegerField()
	fecha = models.DateTimeField(auto_now_add=True)



"""
    def save(self):
    #    super(ModeloPedido, self).save()
    	 m = ModeloProducto.objects.get(pk=self.producto.pk)
    #    m.cantidad = m.cantidad - self.cantidad
    	 m.save()
    #    super(ModeloPedido, self).save()
"""

# Señaleticas ;)
# method for updating
@receiver(post_save, sender=ModeloAbast, dispatch_uid="actualizar_stock")
def update_stock(sender, instance, **kwargs):
    if kwargs.get('created', False):
        m = ModeloProductos.objects.get(pk=instance.producto.pk)
        m.cantidad = m.cantidad + instance.cantidad
        m.save()


@receiver(post_save, sender=ModeloPedido, dispatch_uid="actualizar_stock")
def update_stock(sender, instance, **kwargs):
    if kwargs.get('created', False):
        m = ModeloProductos.objects.get(pk=instance.producto.pk)
        m.cantidad = m.cantidad - instance.cantidad
        m.save()

# La logica del programa la podemos realizar aqui, donde se ingresan los datos
# Si se cargan articulos se suman
# se retiran se restan
# para esto se ocupa post_save es una funcion al final de cada clase del modelo

proyecto/tesis/apps/custom_auth/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.contrib import messages

from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.views.decorators.cache import cache_page
from django.contrib.auth import get_user_model
from django.db.models import Sum, Count, Q
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from datetime import date
from .forms import LoginForm, CargoModelForm, UsuarioModelForm, PerfilesModelForm
import datetime
import socket
from .models import ModeloCargo, UserProfile

now = datetime.datetime.now()
hoy = now.strftime("%w")
tomorrow = now + datetime.timedelta(days=1)
today = date.today()

# En esta parte me vuelvo autista buscando las pifias jajaja
# Esta vista es la que obliga al usuario a logearse, es el coladero de sesiones.


def porciento(cumplimiento, meta):
        return float(cumplimiento) * 100 / float(meta)


#Si revisas esta secuencia de verificacion te daras cuenta que es mas antiguo que la cresta!
# tiene muchas verificaciones lerdas
def Login_view(request):
    mensaje = ""
    user = request.user
    # Aqui pregunto si la sesion usuario se encuentra activa.
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
        # si eta registrado el usuario lo reenvio a la URL / que es la demo
    else:
        if request.method == "POST":
            form = LoginForm(request.POST)

            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                usuario = authenticate(username=username, password=password)
                if usuario is not None and usuario.is_active:
                    #request.session.set_expiry(999999999999)
                    login(request, usuario)

                    user = request.user
                    if user.valid == False:

                        user_info = get_user_model().objects.get(pk = usuario.id)
                        #ValidaSesion(usuario.pk)
                        user_info.valid = True
                        user_info.counter += 1
                        user_info.save()
                    else:
                        sesion = request.session.session_key
                        user_info = get_user_model().objects.get(pk = usuario.id)

                        user_info.counter += 1
                        user_info.save()



                    return HttpResponseRedirect('/')
                else:
                    mensaje = "Datos incorrectos para [ %s ]"%(username)
                    form = LoginForm()
                    ctx = {
                        'form':form,
                        'mensaje':mensaje,
                        }
                    return render(request, 'login/login.html', ctx)
            else:
                form = LoginForm()
                ctx = {
                    'form':form,
                    'mensaje':mensaje,
                    }
                return render(request, 'login/login.html', ctx)
        else:
            form = LoginForm() # Como llamo el form.py saco el formulario de ahi y lo envio al template como contexto.
            ctx = {
                'form':form,
                'mensaje':mensaje,
                }
            return render(request, 'login/login.html', ctx)

#Vista LogOut
def Salir_view(request):
    logout(request)
    return HttpResponseRedirect('/')


# Es solo el nombre del archivo, lo que pasa es que este es django 1.10 y el proyecto es 1.9
# puede ser eso, no se todavia

@login_required(login_url='/login/')
def demo_view(request):
    ctx = {'valor': None}
    return render(request, 'app/home.html', ctx)

# Vista Cargos
def Cargos_view(request):
    if request.POST:
        form = CargoModelForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            messages.add_message(
                request,
                messages.INFO,
                'Cargo Guardado Exitosamente!'
                )
    form = CargoModelForm()
    ctx = {
        'cargos': ModeloCargo.objects.all(),
        'form': form
    }
    return render(request, 'app/cargos.html', ctx)

#Vista Borrar Cargo
def CargoDelete(request, pk):
    ModeloCargo.objects.get(pk=pk).delete()
    messages.add_message(
                request,
                messages.INFO,
                '¡Cargo Eliminado Exitosamente!'
                )
    return HttpResponseRedirect('/charge/add/')

#Vista Actualizar Cargo
def ActualizarDatos(request, pk):
    cargo = ModeloCargo.objects.get(pk=pk)
    if request.method == "POST":
        form = CargoModelForm(request.POST, instance=cargo)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.INFO,
                '¡Cargo Editado Exitosamente!'
                )
            return HttpResponseRedirect('/charge/add/')
    else:
        form = CargoModelForm(instance=cargo)
    ctx = {
        'cargos': ModeloCargo.objects.all(),
        'form': form
    }
    return render(request, 'app/cargar_cargo.html', ctx)
    #return render_to_response("/charge/add/",{"form":form},context_instance=RequestContext(request))

#Vista Pantalla de Bloqueo
def LockScreen_view(request):
    mensaje = ""
    user = request.user
    # Aqui pregunto si la sesion usuario se encuentra activa.
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
        # si eta registrado el usuario lo reenvio a la URL / que es la demo
    else:
        if request.method == "POST":
            form = LoginForm(request.POST)

            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                usuario = authenticate(username=username, password=password)
                if usuario is not None and usuario.is_active:
                    #request.session.set_expiry(999999999999)
                    login(request, usuario)

                    user = request.user
                    if user.valid == False:

                        user_info = get_user_model().objects.get(pk = usuario.id)
                        #ValidaSesion(usuario.pk)
                        user_info.valid = True
                        user_info.counter += 1
                        user_info.save()
                    else:
                        sesion = request.session.session_key
                        user_info = get_user_model().objects.get(pk = usuario.id)

                        user_info.counter += 1
                        user_info.save()



                    return HttpResponseRedirect('/')
                else:
                    mensaje = "Datos incorrectos para [ %s ]"%(username)
                    form = LoginForm()
                    ctx = {
                        'form':form,
                        'mensaje':mensaje,
                        }
                    return render(request, 'login/login.html', ctx)
            else:
                form = LoginForm()
                ctx = {
                    'form':form,
                    'mensaje':mensaje,
                    }
                return render(request, 'login/login.html', ctx)
        else:
            form = LoginForm() # Como llamo el form.py saco el formulario de ahi y lo envio al template como contexto.
            ctx = {
                'form':form,
                'mensaje':mensaje,
                }
            return render(request, 'login/login.html', ctx)


# Vista Crear Usuarios
def Usuarios_view(request):
    if request.POST:
        form = UsuarioModelForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            messages.add_message(
                request,
                messages.INFO,
                'Usuario Guardado Exitosamente!'
                )
    form = UsuarioModelForm()
    ctx = {
        'usuarios': UserProfile.objects.all(),
        'form': form
    }
    return render(request, 'app/usuarios.html', ctx)

# Vista Perfiles
def Perfiles_view(request, hash):
    perfil = UserProfile.objects.get(hash=hash)
    if request.method == "POST":
        form = PerfilesModelForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.INFO,
                '¡Perfil Editado Exitosamente!'
                )
            return HttpResponseRedirect('/user/add/')
    else:
        form = PerfilesModelForm(instance=perfil)
    ctx = {
        'perfiles': UserProfile.objects.all(),
        'form': form
    }
    return render(request, 'app/perfiles.html', ctx)



# Crear usuarios, de la forma mas didactica.
def CrearUser_View(request):
    if request.POST:
        usuario = request.POST.get('usuario', False)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.INFO,
                '¡Usuario Creado Exitosamente!'
                )
            return HttpResponseRedirect('/user/add/')
    else:
        form = PerfilesModelForm(instance=perfil)
    ctx = {
        'perfiles': UserProfile.objects.all(),
        'form': form
    }
    return render(request, 'app/perfiles.html', ctx)

# Vista Directorio
def Directorio_view(request):
    return render(request, 'app/directorio.html')

proyecto/tesis/apps/gestion/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.contrib import messages
import json
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.views.decorators.cache import cache_page
from django.contrib.auth import get_user_model
from django.db.models import Sum, Count, Q
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from datetime import date
from .forms import AbastModelForm
import datetime
import socket
from .models import ModeloAbast
#Importamos modelos de la app productos
from tesis.apps.productos.models import ModeloCategoriaProd, ModeloProductos

#now = datetime.datetime.now()
#hoy = now.strftime("%w")
#tomorrow = now + datetime.timedelta(days=1)
#today = date.today()

#Vista Abastecimiento
def Abastecimiento_view(request):
    if request.POST:
        form = AbastModelForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.solicitante = request.user # Aqui es donde aplica el commit=false, antes de guardar completamos con los datos que queramos.
            f.save()
            messages.add_message(
                request,
                messages.INFO,
                'Abastecimiento Guardado Exitosamente!'
                )
    form = AbastModelForm()
    form.fields['producto'].queryset = ModeloAbast.objects.all()[:0]
    ctx = {
        'abastecimientos': ModeloAbast.objects.all()[:10],
        'form': form
    }
    return render(request, 'app/abastecimiento.html', ctx)

def ws_productos(request):
    id_Categoria = request.GET.get('id_categoria', False)
    results = []
    for dato in ModeloProductos.objects.filter(categoria__pk=id_Categoria):
        results.append({"id":dato.pk, "value": dato.nombre})
    data = json.dumps(results)
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

proyecto/tesis/templates/app/abastecimiento.html
<!-- Estas son las aplicaciones de Block -->
{% extends "base/base.html" %} {% load staticfiles %} {% block titulo %} Abastecimiento {% endblock %} {% block contenido %}
<div class="content">
    <div class="">
        <div class="page-header-title">
            <h4 class="page-title">ABASTECIMIENTO</h4>
        </div>
    </div>
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <h4 class="m-b-30 m-t-0">Abastecimiento de Productos</h4>
                            <h1>Crear Nuevo Abastecimiento<small></small></h1>
                            <div class="panel-body">
                                <h4 class="m-t-0 m-b-30"></h4>
                                <form class="form-horizontal" role="form" action="." method="POST">
                                    {% csrf_token %} {% for field in form %}
                                    <div class="form-group">
                                        <label class="col-md-4 control-label"> {{ field.name }} :</label>
                                        <div class="col-md-5">
                                            {{ field }}
                                            <span class="label label-contrast">{{ field.errors.as_text }}</span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <div class="col-xs-3 col-sm-9 m-b-30" align="right">
                                        <button class="btn btn-default waves-effect waves-light">Guardar</button>
                                    </div>
                                    <!-- Aqui el middleware de los mensajes aparece-->
                                    <div class="col-md-12">
                                        <ul class="messagelist">
                                            {% for message in messages %}
                                            <li class="success">{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-body">
                        <h4 class="m-b-30 m-t-0">Registro de Abastecimientos</h4>
                        <div id="datatable-buttons_filter" class="dataTables_filter">
                        </div>
                        <div id="datatable-buttons_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="datatable-buttons_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 30px; text-align:center;">N°</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 100px; text-align:center;">Solicitante</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 150px; text-align:center;">Producto</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 230px; text-align:center;">Categoría</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 50px; text-align:center;">Cantidad</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 120px; text-align:center;">Fecha</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for dato in abastecimientos %}
                                    <tr role="row" class="odd">
                                        <td class="sorting_1" tabindex="0" align="center">{{forloop.counter}}</td>
                                        <td align="center">{{dato.solicitante}}</td>
                                        <td align="center">{{dato.producto}}</td>
                                        <td align="center">{{dato.categoria}}</td>
                                        <td align="center">{{dato.cantidad}}</td>
                                        <td align="center">{{dato.fecha}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %} {% block jquery %}
<script type="text/javascript" charset="utf-8">
$(function() {
    $("#id_categoria").on('change', function() {
        $.getJSON("{% url 'ws-productos' %}", {
            id_categoria: $("select#id_categoria").val(),
        }, function(data) {
            console.log(data.length);
            var options = '';
            options += '<option selected value>SELECCIONE PRODUCTO...</option>';
            for (var x = 0; x < data.length; x++) {

                options += '<option value="' + data[x]['id'] + '">' + data[x]['value'] + '</option>';


            }
            $('#id_producto').html(options);
        })
    })
})
</script>
{% endblock %}

proyecto/tesis/templates/app/cargar_cargo.html
<!-- Estas son las aplicaciones de Block -->
{% extends "base/base.html" %} {% load staticfiles %} {% block titulo %} Cargos {% endblock %}
{% block contenido %}
<div class="content">
    <div class="">
        <div class="page-header-title">
            <h4 class="page-title">CARGOS</h4>
        </div>
    </div>
    <div class="page-content-wrapper ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <h4 class="m-b-30 m-t-0">Creación y Edición de Roles</h4>
                            <h1>Editar Cargo<small></small></h1>
                            <div class="panel-body">
                                <h4 class="m-t-0 m-b-30"></h4>
                                <form class="form-horizontal" role="form" action="." method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Nombre Cargo :</label>
                                        <div class="col-md-5">
                                            {{form.cargo}}
                                        </div>
                                        <div class="col-xs-6 col-sm-3 m-b-30">
                                            <button class="btn btn-default waves-effect waves-light"> Guardar Edición</button>
                                        </div>
                                        <!-- Aqui el middleware de los mensajes aparece-->
                                        <div class="col-md-12">
                                        <ul class="messagelist">
                                            {% for message in messages %}
                                                <li class="success">{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-body">
                            <h4 class="m-b-30 m-t-0">Listado de Cargos</h4>
                            <div id="datatable-buttons_filter" class="dataTables_filter">
                            </div>
                            <div id="datatable-buttons_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="datatable-buttons_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 30px; text-align:center;">N°</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 200px; text-align:center;">Cargos</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 120px; text-align:center;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for dato in cargos %}
                                        <tr role="row" class="odd">
                                            <td class="sorting_1" tabindex="0" align="center">{{forloop.counter}}</td>
                                            <td>{{dato.cargo}}</td>
                                            <td align="center">
                                            <a href="{% url 'cargar-cargo' dato.pk %}" class="waves-effect"><i class="ion-edit"></i><span> Editar </span></a>
                                            <span>|</span>
                                            <a href="{% url 'borrar-cargo' dato.pk %}" class="waves-effect"><i class="ion-android-trash"></i> <span> Borrar </span></a>                    
                                            </td>
                                            <!--<td><a href="{% url 'borrar-cargo' dato.pk %}">Borrar</a></td>-->
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

proyecto/tesis/templates/app/lista_productos.html
<!-- Estas son las aplicaciones de Block -->
{% extends "base/base.html" %}
{% load staticfiles %}
{% block titulo %} Home {% endblock %}

{% block contenido %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <h4 class="m-b-30 m-t-0">Bordered Table</h4>
                    <div class="row">
                        <div class="col-xs-12">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Categoria</th>
                                        <th>Producto</th>
                                        <th>Cantidad</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for dato in productos %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{dato.categoria}}</td>
                                        <td>{{dato.nombre}}</td>
                                        <td>{{dato.cantidad}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

{% endblock %}